name: Monitor Vercel Deployments

on:
  push:
    branches: [staging, main]
  repository_dispatch:
    types: [vercel-deployment-failed]

jobs:
  monitor-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Wait for Vercel Deployment
        id: wait-deployment
        run: |
          echo "Waiting 2 minutes for Vercel deployment to complete..."
          sleep 120
          
      - name: Check Deployment Status
        id: check-status
        run: |
          # Use Vercel CLI to check deployment status
          npx vercel ls --token ${{ secrets.VERCEL_TOKEN }} > deployments.txt
          
          # Check if latest deployment failed (you would parse the output)
          echo "deployment_status=checking" >> $GITHUB_OUTPUT
          
      - name: Get Build Logs on Failure
        if: failure()
        run: |
          # This would require Vercel API access
          echo "Build failed - would fetch logs here with Vercel API"
          
      - name: Create Issue on Build Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Vercel Deployment Failed',
              body: `
              Deployment failed for commit: ${{ github.sha }}
              Branch: ${{ github.ref_name }}
              
              Please check the Vercel dashboard for detailed logs.
              `,
              labels: ['deployment', 'bug']
            })

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}